image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1172.49976,    0.     ,  982.71849,
            0.     , 1180.23928,  526.4646 ,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.064926, -0.004439, 0.000651, -0.000278, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1230.6626 ,    0.     ,  980.2046 ,    0.     ,
            0.     , 1239.33496,  527.122  ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
