image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [4772.18126,    0.     ,  201.2918 ,
            0.     , 4168.84079, 1030.37713,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.799588, -1.741313, 0.024207, -0.171538, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [4332.29297,    0.     ,  134.22017,    0.     ,
            0.     , 4362.23486, 1042.96424,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
