image_width: 640
image_height: 480
camera_name: camera
camera_matrix:
  rows: 3
  cols: 3
  data: [
            731.9711515438763,
            0,
            337.8548082642976,
            0,
            736.5108518106733,
            247.69196192633015,
            0,
            0,
            1
        ]
distortion_model: rectilinear
distortion_coefficients:
  rows: 1
  cols: 5
  data: [
        0.06738865201992215,
        -0.06802347217138971,
        -0.0011128820441354938,
        0.0037359103409742704,
        0.0963632579036376]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [0,    0.     ,  0,    0.     ,
            0.     , 0, 0,    0.     ,
            0.     ,    0.     ,    0.     ,    0.     ]